name: ExtDN M2 PHPStan
on: [push, pull_request]

jobs:
  phpstan:
    name: M2 PHPStan
    runs-on: ubuntu-latest
    container:
      image: extdn/magento-phpstan-action:8.2-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run PHPStan
        env:
          COMPOSER_NAME: e-conomix/module-dbtranslations
          PHPSTAN_LEVEL: "1"
        run: |
          MAGENTO_ROOT=/m2
          test -d "${MAGENTO_ROOT}" || MAGENTO_ROOT=/var/www/magento2ce

          mkdir -p $MAGENTO_ROOT/local-source/
          cp -R ${GITHUB_WORKSPACE}/. $MAGENTO_ROOT/local-source/

          cd $MAGENTO_ROOT
          composer config repositories.local-source path $MAGENTO_ROOT/local-source/\*
          composer config --no-plugins allow-plugins true
          COMPOSER_MIRROR_PATH_REPOS=1 composer require $COMPOSER_NAME:@dev --no-interaction --dev || exit 1

          CONFIGURATION_FILE=dev/tests/static/testsuite/Magento/Test/Php/_files/phpstan/phpstan.neon
          test -f vendor/${COMPOSER_NAME}/phpstan.neon && CONFIGURATION_FILE=vendor/${COMPOSER_NAME}/phpstan.neon

          php vendor/bin/phpstan analyse \
            --level $PHPSTAN_LEVEL \
            --no-progress \
            --memory-limit=4G \
            --configuration ${CONFIGURATION_FILE} \
            vendor/${COMPOSER_NAME}
